import React, { useEffect, useState } from 'react';
import { RefreshCw, FileText } from 'lucide-react';
import api from '../api/client';
import type { Alert } from '../types';

interface AlertsProps {
  onNavigate: (path: string) => void;
}

export const Alerts: React.FC<AlertsProps> = ({ onNavigate }) => {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [selectedAlert, setSelectedAlert] = useState<any>(null);

  const fetchAlerts = async () => {
    try {
      const res = await api.get('/alerts');
      setAlerts(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, []);

  const updateAlertStatus = async (alertId: number, status: string) => {
    try {
      await api.patch(`/alerts/${alertId}`, { status });
      fetchAlerts();
      if (selectedAlert?.alert?.id === alertId) {
        setSelectedAlert({ ...selectedAlert, alert: { ...selectedAlert.alert, status } });
      }
    } catch (err) {
      console.error(err);
    }
  };

  const inspectAlert = async (id: number) => {
    try {
      const res = await api.get(`/alerts/${id}`);
      setSelectedAlert(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  const escalateToIncident = async (alert: Alert) => {
    try {
      const res = await api.post('/incidents', {
        title: `Incident Escalation: ${alert.alert_type} on ${alert.target_asset}`,
        severity: alert.severity,
        attack_type: alert.alert_type,
        affected_asset: alert.target_asset,
        description: alert.description,
        related_alerts: [alert.id]
      });
      fetchAlerts();
      onNavigate(`/incidents/${res.data.id}`);
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="p-6 space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-white tracking-tight flex items-center gap-2">
            Security Alert Management
            <span className="text-xs bg-purple-950 text-purple-300 border border-purple-800 px-2 py-0.5 rounded font-mono">
              AUTOMATED RULE DETECTION
            </span>
          </h1>
          <p className="text-xs text-slate-400 font-mono">
            Automated alerts generated by CyberShield Detection Engine rules.
          </p>
        </div>
        <button
          onClick={fetchAlerts}
          className="px-3 py-1.5 bg-slate-900 border border-slate-800 text-slate-300 hover:text-white rounded-lg text-xs font-mono flex items-center gap-2"
        >
          <RefreshCw className="w-3.5 h-3.5" />
          <span>Refresh Alerts</span>
        </button>
      </div>

      {/* Alerts Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {alerts.map((al) => (
          <div
            key={al.id}
            className="cyber-card p-6 rounded-2xl border border-slate-800 space-y-4 hover:border-purple-500/50 transition flex flex-col justify-between"
          >
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className={`px-2.5 py-0.5 rounded text-[10px] font-mono font-bold ${
                  al.severity === 'CRITICAL' ? 'bg-rose-950 text-rose-300 border border-rose-800' :
                  al.severity === 'HIGH' ? 'bg-orange-950 text-orange-300 border border-orange-800' :
                  'bg-amber-950 text-amber-300 border border-amber-800'
                }`}>
                  {al.severity}
                </span>
                <span className="text-[10px] font-mono px-2 py-0.5 bg-slate-800 text-slate-300 rounded">
                  {al.status}
                </span>
              </div>

              <div>
                <h3 className="font-bold text-white text-base font-mono">Alert #{al.id}: {al.alert_type}</h3>
                <p className="text-xs text-slate-400 mt-1 leading-relaxed">{al.description}</p>
              </div>

              <div className="space-y-1 font-mono text-[11px] text-slate-400 pt-2 border-t border-slate-900">
                <p>Rule: <span className="text-purple-300">{al.detection_rule}</span></p>
                <p>Source IP: <span className="text-rose-300">{al.source_ip}</span></p>
                <p>Target Asset: <span className="text-slate-200">{al.target_asset}</span></p>
              </div>
            </div>

            <div className="pt-3 border-t border-slate-800 flex items-center gap-2">
              <button
                onClick={() => inspectAlert(al.id)}
                className="flex-1 py-2 bg-slate-900 hover:bg-slate-800 text-slate-200 rounded-lg text-xs font-mono border border-slate-700"
              >
                Investigate
              </button>
              <button
                onClick={() => escalateToIncident(al)}
                className="flex-1 py-2 bg-purple-600 hover:bg-purple-500 text-white rounded-lg text-xs font-bold border border-purple-400/30 flex items-center justify-center gap-1"
              >
                <FileText className="w-3.5 h-3.5" />
                <span>Escalate</span>
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Alert Investigation Modal */}
      {selectedAlert && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-md p-4">
          <div className="bg-slate-900 border border-purple-500/40 rounded-2xl w-full max-w-xl p-6 space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h3 className="font-bold text-white text-base font-mono">Alert #{selectedAlert.alert.id} Details</h3>
              <button onClick={() => setSelectedAlert(null)} className="text-xs text-slate-400 hover:text-white">Close</button>
            </div>

            <div className="space-y-3 text-xs font-mono">
              <p><span className="text-purple-400 font-semibold">Rule:</span> {selectedAlert.alert.detection_rule}</p>
              <p><span className="text-purple-400 font-semibold">Description:</span> {selectedAlert.alert.description}</p>
              
              <div className="space-y-1">
                <label className="text-slate-400">Update Alert Status:</label>
                <div className="flex flex-wrap gap-2">
                  {['NEW', 'ACKNOWLEDGED', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE'].map((st) => (
                    <button
                      key={st}
                      onClick={() => updateAlertStatus(selectedAlert.alert.id, st)}
                      className={`px-2.5 py-1 rounded text-[11px] font-mono border ${
                        selectedAlert.alert.status === st
                          ? 'bg-purple-600 text-white border-purple-400'
                          : 'bg-slate-950 text-slate-400 border-slate-800 hover:border-slate-700'
                      }`}
                    >
                      {st}
                    </button>
                  ))}
                </div>
              </div>

              <div className="pt-2">
                <h4 className="font-bold text-slate-300 mb-2">Related Security Events ({selectedAlert.related_events?.length || 0}):</h4>
                <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 max-h-40 overflow-y-auto space-y-2">
                  {selectedAlert.related_events?.map((ev: any) => (
                    <div key={ev.id} className="text-[11px] border-b border-slate-900 pb-1 last:border-0">
                      <span className="text-purple-400">[{ev.event_type}]</span> {ev.description}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
