import React, { useEffect, useState } from 'react';
import { Download, Plus } from 'lucide-react';
import jsPDF from 'jspdf';
import api from '../api/client';
import type { Report } from '../types';

export const Reports: React.FC = () => {
  const [reports, setReports] = useState<Report[]>([]);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [incidentIdInput, setIncidentIdInput] = useState('1');
  const [loading, setLoading] = useState(false);

  const fetchReports = async () => {
    try {
      const res = await api.get('/reports');
      setReports(res.data);
      if (res.data.length > 0 && !selectedReport) {
        setSelectedReport(res.data[0]);
      }
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const res = await api.post('/reports', { incident_id: parseInt(incidentIdInput, 10) });
      fetchReports();
      setSelectedReport(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleExportPDF = () => {
    if (!selectedReport) return;
    const doc = new jsPDF();
    const c = selectedReport.content_json;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('CYBERSHIELD INCIDENT REPORT', 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Report Code: ${selectedReport.report_code} | Generated By: ${selectedReport.generated_by}`, 14, 28);
    doc.text(`Generated Date: ${new Date(selectedReport.created_at).toLocaleString()}`, 14, 34);

    doc.setLineWidth(0.5);
    doc.line(14, 38, 196, 38);

    doc.setFont('helvetica', 'bold');
    doc.text('1. EXECUTIVE INCIDENT SUMMARY', 14, 46);
    doc.setFont('helvetica', 'normal');
    doc.text(`Incident Title: ${c.incident_title || 'N/A'}`, 14, 54);
    doc.text(`Attack Type: ${c.attack_type || 'N/A'} | Severity: ${c.severity || 'N/A'}`, 14, 60);
    doc.text(`Target Asset: ${c.affected_asset || 'N/A'} | Status: ${c.status || 'N/A'}`, 14, 66);

    const descLines = doc.splitTextToSize(`Description: ${c.description || 'N/A'}`, 180);
    doc.text(descLines, 14, 74);

    let y = 74 + descLines.length * 6;
    doc.setFont('helvetica', 'bold');
    doc.text('2. CONTAINMENT & RECOVERY ACTIONS', 14, y);
    doc.setFont('helvetica', 'normal');
    y += 8;
    const contLines = doc.splitTextToSize(`Containment: ${c.containment_action}`, 180);
    doc.text(contLines, 14, y);
    y += contLines.length * 6;

    const recLines = doc.splitTextToSize(`Recovery & Lessons: ${c.recovery_action}`, 180);
    doc.text(recLines, 14, y);
    y += recLines.length * 6 + 10;

    doc.setFont('helvetica', 'bold');
    doc.text('3. ACADEMIC DISCLOSURE', 14, y);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated inside CyberShield Simulated SOC Laboratory Environment.', 14, y + 6);

    doc.save(`${selectedReport.report_code}.pdf`);
  };

  return (
    <div className="p-6 space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-white tracking-tight flex items-center gap-2">
            Security Incident Report Generator
            <span className="text-xs bg-purple-950 text-purple-300 border border-purple-800 px-2 py-0.5 rounded font-mono">
              EXECUTIVE & TECHNICAL
            </span>
          </h1>
          <p className="text-xs text-slate-400 font-mono">
            Compile formal PDF security incident reports for lab audits & SOC reviews.
          </p>
        </div>

        <div className="flex items-center gap-3 font-mono text-xs">
          <input
            type="number"
            value={incidentIdInput}
            onChange={(e) => setIncidentIdInput(e.target.value)}
            className="w-20 p-2 bg-slate-900 border border-slate-700 rounded text-white text-center"
            placeholder="Inc ID"
          />
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white rounded-lg font-bold shadow flex items-center gap-1.5"
          >
            <Plus className="w-4 h-4" />
            <span>Generate Report</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Reports History Sidebar */}
        <div className="cyber-card p-6 rounded-2xl border border-slate-800 space-y-4">
          <h3 className="font-bold text-white text-sm font-mono border-b border-slate-800 pb-2">
            Generated Reports Archive ({reports.length})
          </h3>
          <div className="space-y-2">
            {reports.map((rep) => (
              <div
                key={rep.id}
                onClick={() => setSelectedReport(rep)}
                className={`p-3 rounded-xl border cursor-pointer font-mono text-xs transition ${
                  selectedReport?.id === rep.id
                    ? 'bg-purple-950/60 border-purple-500 text-white'
                    : 'bg-slate-900 border-slate-800 text-slate-400 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="font-bold text-purple-300">{rep.report_code}</span>
                  <span className="text-[10px] text-slate-500">{new Date(rep.created_at).toLocaleDateString()}</span>
                </div>
                <p className="text-slate-200 mt-1 font-semibold truncate">{rep.title}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Report Preview */}
        <div className="lg:col-span-2 cyber-card p-8 rounded-2xl border border-slate-800 space-y-6">
          {!selectedReport ? (
            <p className="text-xs text-slate-500 font-mono">Select a report to preview.</p>
          ) : (
            <div className="space-y-6">
              <div className="flex items-center justify-between border-b border-slate-800 pb-4">
                <div>
                  <h2 className="text-xl font-extrabold text-white tracking-tight font-mono">
                    CYBERSHIELD INCIDENT REPORT
                  </h2>
                  <p className="text-xs text-purple-400 font-mono mt-0.5">
                    Report ID: {selectedReport.report_code} • Author: {selectedReport.generated_by}
                  </p>
                </div>
                <button
                  onClick={handleExportPDF}
                  className="flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-bold font-mono shadow border border-emerald-400/30"
                >
                  <Download className="w-4 h-4" />
                  <span>Export Official PDF</span>
                </button>
              </div>

              {/* Report Body Details */}
              <div className="space-y-4 font-mono text-xs">
                <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
                  <h4 className="font-bold text-purple-300 uppercase">1. Executive Incident Summary</h4>
                  <div className="grid grid-cols-2 gap-2 text-slate-300 text-[11px]">
                    <p>Incident Title: <span className="text-white font-semibold">{selectedReport.content_json.incident_title}</span></p>
                    <p>Attack Category: <span className="text-white font-semibold">{selectedReport.content_json.attack_type}</span></p>
                    <p>Severity Rating: <span className="text-rose-400 font-bold">{selectedReport.content_json.severity}</span></p>
                    <p>Affected Asset: <span className="text-white font-semibold">{selectedReport.content_json.affected_asset}</span></p>
                  </div>
                  <p className="text-slate-400 text-[11px] pt-1">{selectedReport.content_json.description}</p>
                </div>

                <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
                  <h4 className="font-bold text-purple-300 uppercase">2. Detection & Alerts Summary</h4>
                  <p className="text-slate-400 text-[11px]">
                    Correlated Alerts Count: {selectedReport.content_json.alerts_count}
                  </p>
                  <div className="space-y-1">
                    {selectedReport.content_json.alerts_summary?.map((a: any) => (
                      <div key={a.id} className="text-[11px] text-slate-300">• [{a.type}] Rule: {a.rule} ({a.severity})</div>
                    ))}
                  </div>
                </div>

                <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
                  <h4 className="font-bold text-purple-300 uppercase">3. Containment & Remediation Actions</h4>
                  <p className="text-slate-200"><span className="text-amber-400 font-bold">Containment:</span> {selectedReport.content_json.containment_action}</p>
                  <p className="text-slate-200"><span className="text-emerald-400 font-bold">Recovery:</span> {selectedReport.content_json.recovery_action}</p>
                  <p className="text-slate-200"><span className="text-purple-400 font-bold">Resolution:</span> {selectedReport.content_json.resolution_notes}</p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
